stackclient: stackclient.o stackADT3.o stackADT.h
	gcc stackclient.o stackADT3.o -o stackclient
stackclient.o: stackclient.c stackADT.h
	gcc -c stackclient.c
stackADT3.o: stackADT3.c stackADT.h
	gcc -c stackADT3.c